### ISSUE TITLE
NextJS: Update API URL (Production) to point to Digital Oceans 

### ISSUE THREAD

**Issue by aggarwal-h** [HKanwal/kapstone#71]
The backend is now deployed on Digital Oceans and can be accessed here: https://walrus-app-5juci.ondigitalocean.app/.

The only thing remaining is to update the frontend to point to this URL.

**Comment by HKanwal** [comment]
@aggarwal-h Since DEBUG = false, CORS issues arise.

**Comment by HKanwal** [comment]
I think we should just disable CORS altogether, both is development and in prod.

**Comment by HKanwal** [comment]
Fortunately, I did get the Python server running on my laptop, so we can keep that as a backup plan for the demo.

**Comment by aggarwal-h** [comment]
@HKanwal try adding this:
```python3
if not DEBUG:
    CORS_ALLOWED_ORIGINS = ["https://walrus-app-5juci.ondigitalocean.app/"]
```
Source: https://stackoverflow.com/a/35761088

**Comment by aggarwal-h** [comment]
@hark Add this url to the NextJS endpoint: https://walrus-app-5juci.ondigitalocean.app/.

Then, let me know the URL that your app gets deployed to. I will add it to Digital Oceans environment variable.
